### ISSUE TITLE
Create Paper Protototype

### ISSUE THREAD

**Issue by cmcahoon01** [carsondrobe/Fellas#1]
Draw a basic mockup of the dashboard. Include a potential visualization of each of the planned widgets/data values. Include buttons for logging in and submitting feedback

**Comment by cmcahoon01** [comment]
[Weather_Dashboard_Prototype_2.pdf](https://github.com/carsondrobe/Fellas/files/14380602/Weather_Dashboard_Prototype_2.pdf)
[Weather_Dashboard_Prototype_1.pdf](https://github.com/carsondrobe/Fellas/files/14380601/Weather_Dashboard_Prototype_1.pdf)

**Comment by abijeet-dhillon** [comment]
Both look good. 

Prototype 1 is nice since it is only 1 page and all the information is available at a glance, we could also add a popup when a user hovers over abbreviated information (e.g. hovering over DMC would have a duff moisture code popup). 

Prototype 2 is more visually appealing, we could implement a scroll feature of the right column which will allow users to scroll between weather and fire information system and the left column (the map) could remain in place rather than make it 2 pages.

**Comment by carsondrobe** [comment]
I consider this a complete Paper Prototype, marking this as Done

**Comment by Davis245** [comment]
[Final Paper Prototype](https://github.com/carsondrobe/Fellas/blob/main/Paper_Prototype.pdf)
