### ISSUE TITLE
Update Map.js to reflect current data

### ISSUE THREAD

**Issue by robertyac** [carsondrobe/Fellas#157]
Update map.js to reflect current up-to-date data instead of 12:00 PM

Maybe include a time picker as well?

**Comment by robertyac** [comment]
Keeping in mind that "Filtering" is apart of the minimum requirements for the project

**Comment by abijeet-dhillon** [comment]
I think we should implement a time picker as part of the date picker, that way users will be able to filter the data by the hour (which will be most useful for our users (firefighters) since I am assuming they would like to see how to weather/data has changed in the last couple of hours in order to predict fire conditions).

**Comment by robertyac** [comment]
I agree it would probably be the most straight forward way to implement for
our current timeline.

**Comment by robertyac** [comment]
With the bot this issue is now tasked to update map.js to reflect current up to date data instead of 12:00PM
