### ISSUE TITLE
Find a way to incorporate a map into our dashboard.

### ISSUE THREAD

**Issue by cmcahoon01** [carsondrobe/Fellas#4]
Test if google map api will work for our needs. Get a script to display a map with several of our weather stations on it. If Google's map api won't work, find an alternative.

**Comment by cmcahoon01** [comment]
Glance at how difficult Leaflet is to use

**Comment by robertyac** [comment]
example: https://www.arcgis.com/apps/webappviewer/index.html?id=c36baf74b74a46978cf517579a9ee332

**Comment by abijeet-dhillon** [comment]
Decided to go with a Leaflet map since it seems to have lots of documentation online and is easy to set up and use. The popup/markers are also customizable through CSS and the style of the map is customizable also. I have attached a picture of an initial implementation just for reference.

![Image](https://github.com/carsondrobe/Fellas/assets/112976240/8a91968d-9ca9-4a7b-ac15-4250ede08ce5)

Code for this initial implementation can be found on the map branch as well.

**Comment by carsondrobe** [comment]
This looks great to me!
